containers:
  container1:
    seconds: 0
    minutes: 5
    hours: 0
    randomMessage: true
    messages:
      - "Hello everyone!"
      - "This is example tips message."
  container2:
    seconds: 0
    minutes: 0
    hours: 24
    randomMessage: false
    messages:
      - "A day finished."